name: heat_PINNS
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.8.4
  - scikit-learn=1.6.1
  - ipython=8.18.1
  - ipykernel=6.29.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - mpmath=1.3.0
  - networkx=3.2.1
  - pillow=11.1.0
  - sympy=1.13.1
  - tornado=6.4.2
  - tqdm=4.66.4
  - pytorch=2.6.0
  - torchvision=0.21.0
  - torchaudio=2.6.0
  - cudatoolkit=11.8
  - pip
  - pip:
    - asttokens==3.0.0
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - debugpy==1.8.13
    - decorator==5.2.1
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - filelock==3.18.0
    - fonttools==4.57.0
    - fsspec==2025.3.2
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - intel-openmp==2021.4.0
    - jedi==0.19.2
    - Jinja2==3.1.6
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - MarkupSafe==3.0.2
    - matplotlib-inline==0.1.7
    - nest-asyncio==1.6.0
    - packaging==24.2
    - parso==0.8.4
    - psutil==7.0.0
    - pure_eval==0.2.3
    - pyDOE==0.3.8
    - Pygments==2.19.1
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pywin32==310
    - pyzmq==26.4.0
    - setuptools==75.8.0
    - six==1.17.0
    - stack-data==0.6.3
    - tbb==2021.13.1
    - threadpoolctl==3.6.0
    - traitlets==5.14.3
    - typing-extensions==4.13.1
    - wcwidth==0.2.13
    - wheel==0.45.1
    - zipp==3.21.0
